### ISSUE TITLE
Redundant shim return?

### ISSUE THREAD

**Issue by syranide** [ljharb/object.assign#10]
https://github.com/ljharb/object.assign/blob/master/index.js#L27

Surely just returning `Object.assign` is identical? I'm curious, what's even the point of returning from the shim-method (the whole point is to shim the global)?

**Comment by ljharb** [comment]
Simply so it's chainable. Otherwise, you can't do `var assign = require('object.assign').shim();`, you'd have to do it in two lines.

**Comment by ljharb** [comment]
In other words, just because it's modifying the global doesn't mean you have to use it as a global in your code.

**Comment by syranide** [comment]
@ljharb I guess that makes sense, but it still seems like `return Object.assign` should be enough given that it's explicitly shimmed the line before it.
