### ISSUE TITLE
UMD Wrapper

### ISSUE THREAD

**Issue by swashcap** [ljharb/object.assign#13]
Would you consider bundling a script with a [UMD Wrapper](https://github.com/umdjs/umd)? It would make it easier to use this module in browser _and_ Node-like environments.

**Comment by ljharb** [comment]
That's already easy via a browserify transform - at this point (2015) i'm no longer interested in maintaining UMD workarounds, when `browserify` handles everything wonderfully.

This module already includes a [browserify entry point](https://github.com/ljharb/object.assign/blob/master/browserShim.js), so a browser build will also auto-shim itself.
