### ISSUE TITLE
shim by default?

### ISSUE THREAD

**Issue by briandipalma** [ljharb/object.assign#4]
Thanks for the shim, I was wondering why the shim acts differently to other ones though. Normally you include a shim and it adds itself to the environment if what it's shimming doesn't exist. This shim requires you to call `shim` on the exported object.

Why the different behaviour? Would it be OK to change it to act like other shims?

**Comment by ljharb** [comment]
@briandipalma Would a `browserify` entry point solve this for you? Specifically, the way I implemented https://github.com/es-shims/es7-shim - that `require` in node won't auto-shim, but you can call `shim()` on it - but that browserify's build *will* auto-shim.

**Comment by briandipalma** [comment]
Sadly I don't use browserify, but thanks for mentioning this.
