### ISSUE TITLE
Patch level update to 4.1.1 to pull in some of the updated dependencies

### ISSUE THREAD

**Issue by marekventur** [ljharb/object.assign#74]
Hi!

Would it be possible to release a patch-version level release for this? 

I'm especially excited for `"object-keys": "^1.1.1"`, which should get rid of some of the warnings we're [currently seeing in firefox](https://github.com/ljharb/object-keys/blob/v1.1.1/CHANGELOG.md#111--2019-04-06).

Please let me know if I can be of any help with this!

Cheers,
Marek

**Comment by ljharb** [comment]
The semver range on the dependency uses `^`, so anything in the v1 line automatically satisfies the dependency. If you're not using a lockfile, you get this for free; if you are, try just `npm install --save object.assign` which I believe will update all of its transitive deps to the latest?

**Comment by marekventur** [comment]
sorry, a lock file was the problem. Thank you!
