### ISSUE TITLE
v4.1.4 hasn't made it's way onto the Yarnpkg repository

### ISSUE THREAD

**Issue by geoidesic** [ljharb/object.assign#84]
Is this something you have to do manually or what?

**Comment by ljharb** [comment]
There is no yarn repository - it’s just npm, with a domain name in front. afaik it’s not possible for anything to be on npm and not in yarnpkg.

**Comment by geoidesic** [comment]
Ok good to know! However...

1. Why then am I getting this error?
```
error An unexpected error occurred: "https://registry.yarnpkg.com/object.assign/-/object.assign-4.1.4.tgz: incorrect data check".
```

2. Why does the tar.gz file exist but it's not listed on npm or yarnpkg?

https://www.npmjs.com/package/object-assign?activeTab=versions
https://yarnpkg.com/package/object-assign

**Comment by ljharb** [comment]
Because that’s an entirely different package - note the dash vs the dot.
