### ISSUE TITLE
The npm package size is 1MB because of test.html

### ISSUE THREAD

**Issue by nickolay** [ljharb/object.assign#85]
Installing this package in a new projects results in a >1MB node_modules:

    $ mkdir test && cd test
    $ npm init -y
    $ npm i object.assign
    added 13 packages, and audited 14 packages in 838ms
    $ du -hs node_modules/object.assign
    1.2M	node_modules/object.assign

This is consistent with https://www.npmjs.com/package/object.assign reporting the "unpacked size" of 1.17 MB.

Most this is a single file node_modules/object.assign/test.html weighing a full megabyte. Given that this package has 30M weekly downloads, would you consider removing it from the package?

**Comment by ljharb** [comment]
whoops, including that file is definitely a mistake, it's just bundler output for testing. I'll absolutely publish a patch removing it.

**Comment by ljharb** [comment]
v4.1.5 published. Thanks for calling that out!
