### ISSUE TITLE
Malware warning in version 4.1.7

### ISSUE THREAD

**Issue by jawandarajbir** [ljharb/object.assign#87]
Hi @ljharb , 

I encountered a malware warning today when using version 4.1.7. 
![image](https://github.com/user-attachments/assets/09d3477d-cd5b-4754-a486-91d6b2e11e6a)

`npm install` command is failing.
![image](https://github.com/user-attachments/assets/015809ab-4c7d-4699-bd77-c4e4ed4bae82)

Could you please investigate version 4.1.7 for potential malware

**Comment by ljharb** [comment]
There is no malware, it’s a perfectly legit version; i have no idea why it would be flagged as malware.

**Comment by ljharb** [comment]
Can you please inquire with your IT desk and find out why it was wrongly flagged?

**Comment by rjawanda-cos** [comment]
Thanks @ljharb 
I'll follow up with IT to find more details here.

**Comment by jawandarajbir** [comment]
Thanks @ljharb 
I'll follow up with IT to find more details here.

**Comment by jawandarajbir** [comment]
I did some analysis using https://www.virustotal.com/

Version 4.1.7
* 6/61 security vendors flagged this file as malicious
* File scanned = https://registry.npmjs.org/object.assign/-/object.assign-4.1.7.tgz
* Full report = https://www.virustotal.com/gui/file/08e4dcd218f7ac619100ac3d3bb76b54c66257cabf0b2409dbfbb6dff01bfcf3/detection
![image](https://github.com/user-attachments/assets/ce961fe9-1773-4cc3-8035-11f52d5da2b4)
* This means there are other users facing same issue


Version 4.1.5
* No security vendors flagged this file as malicious
* File scanned = https://registry.npmjs.org/object.assign/-/object.assign-4.1.5.tgz
* Full report = https://www.virustotal.com/gui/file/f46a439010bacef0b69f3d090655469a14e5aa1729315df088fd1ecf6868def7

**Comment by ljharb** [comment]
Thanks for the context. That doesn't make any sense; it's 100% not malicious. I assume it's just that it's been over a year since I published the last version, or something?

**Comment by ljharb** [comment]
If you could figure out which security vendors have these false positives, I'd love to reach out to them directly so they can fix their bug.

**Comment by JGreenlee** [comment]
I am facing this as well. I found that 4.1.7 and 4.1.6 are affected, but 4.1.5 is not affected.

**Comment by ljharb** [comment]
That's great progress! I'd love to know which vendor is the holdout :-)

**Comment by ljharb** [comment]
Looks like the last false positive is now corrected.

**Comment by jawandarajbir** [comment]
The malware warning is gone from my work machine as well 👍

Thanks @ljharb
